//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPKeeper.Cmd.VatSvr {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", ConfigurationName="VatSvr.vatserviceRD3Soap")]
    public interface vatserviceRD3Soap {
        
        // CODEGEN: Generating message contract since element name username from namespace https://rdws.rd.go.th/serviceRD3/vatserviceRD3 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/serviceRD3/vatserviceRD3/Service", ReplyAction="*")]
        ERPKeeper.Cmd.VatSvr.ServiceResponse Service(ERPKeeper.Cmd.VatSvr.ServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/serviceRD3/vatserviceRD3/Service", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPKeeper.Cmd.VatSvr.ServiceResponse> ServiceAsync(ERPKeeper.Cmd.VatSvr.ServiceRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace https://rdws.rd.go.th/serviceRD3/vatserviceRD3 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/serviceRD3/vatserviceRD3/ServiceArr", ReplyAction="*")]
        ERPKeeper.Cmd.VatSvr.ServiceArrResponse ServiceArr(ERPKeeper.Cmd.VatSvr.ServiceArrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/serviceRD3/vatserviceRD3/ServiceArr", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPKeeper.Cmd.VatSvr.ServiceArrResponse> ServiceArrAsync(ERPKeeper.Cmd.VatSvr.ServiceArrRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Service", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", Order=0)]
        public ERPKeeper.Cmd.VatSvr.ServiceRequestBody Body;
        
        public ServiceRequest() {
        }
        
        public ServiceRequest(ERPKeeper.Cmd.VatSvr.ServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    public partial class ServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TIN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ProvinceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int BranchNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int AmphurCode;
        
        public ServiceRequestBody() {
        }
        
        public ServiceRequestBody(string username, string password, string TIN, string Name, int ProvinceCode, int BranchNumber, int AmphurCode) {
            this.username = username;
            this.password = password;
            this.TIN = TIN;
            this.Name = Name;
            this.ProvinceCode = ProvinceCode;
            this.BranchNumber = BranchNumber;
            this.AmphurCode = AmphurCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceResponse", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", Order=0)]
        public ERPKeeper.Cmd.VatSvr.ServiceResponseBody Body;
        
        public ServiceResponse() {
        }
        
        public ServiceResponse(ERPKeeper.Cmd.VatSvr.ServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    public partial class ServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERPKeeper.RdVat.vat ServiceResult;
        
        public ServiceResponseBody() {
        }
        
        public ServiceResponseBody(ERPKeeper.RdVat.vat ServiceResult) {
            this.ServiceResult = ServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceArrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceArr", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", Order=0)]
        public ERPKeeper.Cmd.VatSvr.ServiceArrRequestBody Body;
        
        public ServiceArrRequest() {
        }
        
        public ServiceArrRequest(ERPKeeper.Cmd.VatSvr.ServiceArrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    public partial class ServiceArrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ERPKeeper.Cmd.VatSvr.ArrayOfString TINs;
        
        public ServiceArrRequestBody() {
        }
        
        public ServiceArrRequestBody(string username, string password, ERPKeeper.Cmd.VatSvr.ArrayOfString TINs) {
            this.username = username;
            this.password = password;
            this.TINs = TINs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceArrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceArrResponse", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", Order=0)]
        public ERPKeeper.Cmd.VatSvr.ServiceArrResponseBody Body;
        
        public ServiceArrResponse() {
        }
        
        public ServiceArrResponse(ERPKeeper.Cmd.VatSvr.ServiceArrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    public partial class ServiceArrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERPKeeper.RdVat.vat ServiceArrResult;
        
        public ServiceArrResponseBody() {
        }
        
        public ServiceArrResponseBody(ERPKeeper.RdVat.vat ServiceArrResult) {
            this.ServiceArrResult = ServiceArrResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface vatserviceRD3SoapChannel : ERPKeeper.Cmd.VatSvr.vatserviceRD3Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class vatserviceRD3SoapClient : System.ServiceModel.ClientBase<ERPKeeper.Cmd.VatSvr.vatserviceRD3Soap>, ERPKeeper.Cmd.VatSvr.vatserviceRD3Soap {
        
        public vatserviceRD3SoapClient() {
        }
        
        public vatserviceRD3SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public vatserviceRD3SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public vatserviceRD3SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public vatserviceRD3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPKeeper.Cmd.VatSvr.ServiceResponse ERPKeeper.Cmd.VatSvr.vatserviceRD3Soap.Service(ERPKeeper.Cmd.VatSvr.ServiceRequest request) {
            return base.Channel.Service(request);
        }
        
        public ERPKeeper.RdVat.vat Service(string username, string password, string TIN, string Name, int ProvinceCode, int BranchNumber, int AmphurCode) {
            ERPKeeper.Cmd.VatSvr.ServiceRequest inValue = new ERPKeeper.Cmd.VatSvr.ServiceRequest();
            inValue.Body = new ERPKeeper.Cmd.VatSvr.ServiceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TIN = TIN;
            inValue.Body.Name = Name;
            inValue.Body.ProvinceCode = ProvinceCode;
            inValue.Body.BranchNumber = BranchNumber;
            inValue.Body.AmphurCode = AmphurCode;
            ERPKeeper.Cmd.VatSvr.ServiceResponse retVal = ((ERPKeeper.Cmd.VatSvr.vatserviceRD3Soap)(this)).Service(inValue);
            return retVal.Body.ServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPKeeper.Cmd.VatSvr.ServiceResponse> ERPKeeper.Cmd.VatSvr.vatserviceRD3Soap.ServiceAsync(ERPKeeper.Cmd.VatSvr.ServiceRequest request) {
            return base.Channel.ServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPKeeper.Cmd.VatSvr.ServiceResponse> ServiceAsync(string username, string password, string TIN, string Name, int ProvinceCode, int BranchNumber, int AmphurCode) {
            ERPKeeper.Cmd.VatSvr.ServiceRequest inValue = new ERPKeeper.Cmd.VatSvr.ServiceRequest();
            inValue.Body = new ERPKeeper.Cmd.VatSvr.ServiceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TIN = TIN;
            inValue.Body.Name = Name;
            inValue.Body.ProvinceCode = ProvinceCode;
            inValue.Body.BranchNumber = BranchNumber;
            inValue.Body.AmphurCode = AmphurCode;
            return ((ERPKeeper.Cmd.VatSvr.vatserviceRD3Soap)(this)).ServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPKeeper.Cmd.VatSvr.ServiceArrResponse ERPKeeper.Cmd.VatSvr.vatserviceRD3Soap.ServiceArr(ERPKeeper.Cmd.VatSvr.ServiceArrRequest request) {
            return base.Channel.ServiceArr(request);
        }
        
        public ERPKeeper.RdVat.vat ServiceArr(string username, string password, ERPKeeper.Cmd.VatSvr.ArrayOfString TINs) {
            ERPKeeper.Cmd.VatSvr.ServiceArrRequest inValue = new ERPKeeper.Cmd.VatSvr.ServiceArrRequest();
            inValue.Body = new ERPKeeper.Cmd.VatSvr.ServiceArrRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TINs = TINs;
            ERPKeeper.Cmd.VatSvr.ServiceArrResponse retVal = ((ERPKeeper.Cmd.VatSvr.vatserviceRD3Soap)(this)).ServiceArr(inValue);
            return retVal.Body.ServiceArrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPKeeper.Cmd.VatSvr.ServiceArrResponse> ERPKeeper.Cmd.VatSvr.vatserviceRD3Soap.ServiceArrAsync(ERPKeeper.Cmd.VatSvr.ServiceArrRequest request) {
            return base.Channel.ServiceArrAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPKeeper.Cmd.VatSvr.ServiceArrResponse> ServiceArrAsync(string username, string password, ERPKeeper.Cmd.VatSvr.ArrayOfString TINs) {
            ERPKeeper.Cmd.VatSvr.ServiceArrRequest inValue = new ERPKeeper.Cmd.VatSvr.ServiceArrRequest();
            inValue.Body = new ERPKeeper.Cmd.VatSvr.ServiceArrRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TINs = TINs;
            return ((ERPKeeper.Cmd.VatSvr.vatserviceRD3Soap)(this)).ServiceArrAsync(inValue);
        }
    }
}
