//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPKeeper.WebFrontEnd.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERPKeeper.WebFrontEnd.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountants.
        /// </summary>
        public static string Accountants {
            get {
                return ResourceManager.GetString("Accountants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Groups.
        /// </summary>
        public static string AccountGroups {
            get {
                return ResourceManager.GetString("AccountGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to เพิ่ม.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Commecial Role.
        /// </summary>
        public static string AddCommecialRole {
            get {
                return ResourceManager.GetString("AddCommecialRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Payment.
        /// </summary>
        public static string AdvancePayment {
            get {
                return ResourceManager.GetString("AdvancePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Accounts.
        /// </summary>
        public static string AssetAccounts {
            get {
                return ResourceManager.GetString("AssetAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string AssetTypes {
            get {
                return ResourceManager.GetString("AssetTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Sheet.
        /// </summary>
        public static string BalanceSheet {
            get {
                return ResourceManager.GetString("BalanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        public static string BankAccount {
            get {
                return ResourceManager.GetString("BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Accounts.
        /// </summary>
        public static string BankAccounts {
            get {
                return ResourceManager.GetString("BankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills Of Materials.
        /// </summary>
        public static string Estimates {
            get {
                return ResourceManager.GetString("Estimates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string Brands {
            get {
                return ResourceManager.GetString("Brands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BusinessDirectory.
        /// </summary>
        public static string BusinessDirectory {
            get {
                return ResourceManager.GetString("BusinessDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancle.
        /// </summary>
        public static string Cancle {
            get {
                return ResourceManager.GetString("Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital.
        /// </summary>
        public static string Capital {
            get {
                return ResourceManager.GetString("Capital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capital Activity.
        /// </summary>
        public static string CapitalActivity {
            get {
                return ResourceManager.GetString("CapitalActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        public static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases.
        /// </summary>
        public static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Account.
        /// </summary>
        public static string CashAccount {
            get {
                return ResourceManager.GetString("CashAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Payment.
        /// </summary>
        public static string CashPayment {
            get {
                return ResourceManager.GetString("CashPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Of Account.
        /// </summary>
        public static string ChartOfAccount {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercials.
        /// </summary>
        public static string Commercials {
            get {
                return ResourceManager.GetString("Commercials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercials.
        /// </summary>
        public static string CommercialTaxes {
            get {
                return ResourceManager.GetString("CommercialTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coperate Tax.
        /// </summary>
        public static string CoperateTax {
            get {
                return ResourceManager.GetString("CoperateTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoperateTaxes.
        /// </summary>
        public static string CoperateTaxes {
            get {
                return ResourceManager.GetString("CoperateTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costing.
        /// </summary>
        public static string Costing {
            get {
                return ResourceManager.GetString("Costing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COSG.
        /// </summary>
        public static string CostOfGoodsSold {
            get {
                return ResourceManager.GetString("CostOfGoodsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashBoard.
        /// </summary>
        public static string DashBoard {
            get {
                return ResourceManager.GetString("DashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprecated Schedules.
        /// </summary>
        public static string DeprecateSchedules {
            get {
                return ResourceManager.GetString("DeprecateSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprecation.
        /// </summary>
        public static string Deprecation {
            get {
                return ResourceManager.GetString("Deprecation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Groups.
        /// </summary>
        public static string DocumentGroups {
            get {
                return ResourceManager.GetString("DocumentGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string Due {
            get {
                return ResourceManager.GetString("Due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earnest Receives.
        /// </summary>
        public static string EarnestReceives {
            get {
                return ResourceManager.GetString("EarnestReceives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation.
        /// </summary>
        public static string Estimation {
            get {
                return ResourceManager.GetString("Estimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation Item.
        /// </summary>
        public static string EstimationItem {
            get {
                return ResourceManager.GetString("EstimationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation Items.
        /// </summary>
        public static string EstimationItems {
            get {
                return ResourceManager.GetString("EstimationItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log.
        /// </summary>
        public static string EventLog {
            get {
                return ResourceManager.GetString("EventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Logs.
        /// </summary>
        public static string EventLogs {
            get {
                return ResourceManager.GetString("EventLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Account.
        /// </summary>
        public static string FavoriteAccount {
            get {
                return ResourceManager.GetString("FavoriteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial.
        /// </summary>
        public static string Financial {
            get {
                return ResourceManager.GetString("Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Accounts.
        /// </summary>
        public static string FinancialAccounts {
            get {
                return ResourceManager.GetString("FinancialAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Year.
        /// </summary>
        public static string FiscalYear {
            get {
                return ResourceManager.GetString("FiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string FixedAsset {
            get {
                return ResourceManager.GetString("FixedAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string FixedAssets {
            get {
                return ResourceManager.GetString("FixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Types.
        /// </summary>
        public static string FixedAssetTypes {
            get {
                return ResourceManager.GetString("FixedAssetTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fund Transfers.
        /// </summary>
        public static string FundTransfers {
            get {
                return ResourceManager.GetString("FundTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Porfit.
        /// </summary>
        public static string GrossPorfit {
            get {
                return ResourceManager.GetString("GrossPorfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Center.
        /// </summary>
        public static string HelpCenter {
            get {
                return ResourceManager.GetString("HelpCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomes.
        /// </summary>
        public static string Incomes {
            get {
                return ResourceManager.GetString("Incomes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Statement.
        /// </summary>
        public static string IncomeStatement {
            get {
                return ResourceManager.GetString("IncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Tax.
        /// </summary>
        public static string IncomeTax {
            get {
                return ResourceManager.GetString("IncomeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Taxes.
        /// </summary>
        public static string IncomeTaxes {
            get {
                return ResourceManager.GetString("IncomeTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment.
        /// </summary>
        public static string Investment {
            get {
                return ResourceManager.GetString("Investment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investments.
        /// </summary>
        public static string Investments {
            get {
                return ResourceManager.GetString("Investments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investors.
        /// </summary>
        public static string Investors {
            get {
                return ResourceManager.GetString("Investors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Groups.
        /// </summary>
        public static string ItemGroups {
            get {
                return ResourceManager.GetString("ItemGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Entries.
        /// </summary>
        public static string JournalEntries {
            get {
                return ResourceManager.GetString("JournalEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Entry Types.
        /// </summary>
        public static string JournalEntryTypes {
            get {
                return ResourceManager.GetString("JournalEntryTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger.
        /// </summary>
        public static string Ledgers {
            get {
                return ResourceManager.GetString("Ledgers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lend.
        /// </summary>
        public static string Lend {
            get {
                return ResourceManager.GetString("Lend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lends.
        /// </summary>
        public static string Lends {
            get {
                return ResourceManager.GetString("Lends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liability.
        /// </summary>
        public static string Liability {
            get {
                return ResourceManager.GetString("Liability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liability Accounts.
        /// </summary>
        public static string LiabilityAccounts {
            get {
                return ResourceManager.GetString("LiabilityAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liability Payments.
        /// </summary>
        public static string LiabilityPayments {
            get {
                return ResourceManager.GetString("LiabilityPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liability Payment Types.
        /// </summary>
        public static string LiabilityPaymentTypes {
            get {
                return ResourceManager.GetString("LiabilityPaymentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        public static string Loan {
            get {
                return ResourceManager.GetString("Loan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans.
        /// </summary>
        public static string Loans {
            get {
                return ResourceManager.GetString("Loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Deprecated Asset.
        /// </summary>
        public static string NonDeprecatedAsset {
            get {
                return ResourceManager.GetString("NonDeprecatedAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Inventory.
        /// </summary>
        public static string NonInventory {
            get {
                return ResourceManager.GetString("NonInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotDue.
        /// </summary>
        public static string NotDue {
            get {
                return ResourceManager.GetString("NotDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance.
        /// </summary>
        public static string OpeningBalance {
            get {
                return ResourceManager.GetString("OpeningBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Task.
        /// </summary>
        public static string OpenTask {
            get {
                return ResourceManager.GetString("OpenTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations.
        /// </summary>
        public static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Due.
        /// </summary>
        public static string OverDue {
            get {
                return ResourceManager.GetString("OverDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartialPaid.
        /// </summary>
        public static string PartialPaid {
            get {
                return ResourceManager.GetString("PartialPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        public static string PartNumber {
            get {
                return ResourceManager.GetString("PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Period.
        /// </summary>
        public static string PaymentPeriod {
            get {
                return ResourceManager.GetString("PaymentPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Periods.
        /// </summary>
        public static string PaymentPeriods {
            get {
                return ResourceManager.GetString("PaymentPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retentions.
        /// </summary>
        public static string PaymentRetentions {
            get {
                return ResourceManager.GetString("PaymentRetentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Stubs.
        /// </summary>
        public static string PaymentStubs {
            get {
                return ResourceManager.GetString("PaymentStubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentTemplate.
        /// </summary>
        public static string PaymentTemplate {
            get {
                return ResourceManager.GetString("PaymentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        public static string Periods {
            get {
                return ResourceManager.GetString("Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        public static string Persons {
            get {
                return ResourceManager.GetString("Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit And Lost.
        /// </summary>
        public static string ProfitAndLost {
            get {
                return ResourceManager.GetString("ProfitAndLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Orders.
        /// </summary>
        public static string PurchaseOrders {
            get {
                return ResourceManager.GetString("PurchaseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Quote.
        /// </summary>
        public static string PurchaseQuote {
            get {
                return ResourceManager.GetString("PurchaseQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Quotes.
        /// </summary>
        public static string PurchaseQuotes {
            get {
                return ResourceManager.GetString("PurchaseQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Return.
        /// </summary>
        public static string PurchaseReturn {
            get {
                return ResourceManager.GetString("PurchaseReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchases.
        /// </summary>
        public static string Purchases {
            get {
                return ResourceManager.GetString("Purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation.
        /// </summary>
        public static string Quotation {
            get {
                return ResourceManager.GetString("Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes.
        /// </summary>
        public static string Quotes {
            get {
                return ResourceManager.GetString("Quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Payments.
        /// </summary>
        public static string ReceivePayments {
            get {
                return ResourceManager.GetString("ReceivePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Payment Types.
        /// </summary>
        public static string ReceivePaymentTypes {
            get {
                return ResourceManager.GetString("ReceivePaymentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Account.
        /// </summary>
        public static string RelatedAccount {
            get {
                return ResourceManager.GetString("RelatedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retain Earning.
        /// </summary>
        public static string RetainEarning {
            get {
                return ResourceManager.GetString("RetainEarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention.
        /// </summary>
        public static string Retention {
            get {
                return ResourceManager.GetString("Retention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention Payments.
        /// </summary>
        public static string RetentionPayments {
            get {
                return ResourceManager.GetString("RetentionPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retentions.
        /// </summary>
        public static string Retentions {
            get {
                return ResourceManager.GetString("Retentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention Types.
        /// </summary>
        public static string RetentionTypes {
            get {
                return ResourceManager.GetString("RetentionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Quote.
        /// </summary>
        public static string SaleQuote {
            get {
                return ResourceManager.GetString("SaleQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Quotes.
        /// </summary>
        public static string SaleQuotes {
            get {
                return ResourceManager.GetString("SaleQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesOrder.
        /// </summary>
        public static string SalesOrder {
            get {
                return ResourceManager.GetString("SalesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Orders.
        /// </summary>
        public static string SalesOrders {
            get {
                return ResourceManager.GetString("SalesOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Return.
        /// </summary>
        public static string SalesReturn {
            get {
                return ResourceManager.GetString("SalesReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Returns.
        /// </summary>
        public static string SalesReturns {
            get {
                return ResourceManager.GetString("SalesReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax.
        /// </summary>
        public static string SalesTax {
            get {
                return ResourceManager.GetString("SalesTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment.
        /// </summary>
        public static string Shipment {
            get {
                return ResourceManager.GetString("Shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipments.
        /// </summary>
        public static string Shipments {
            get {
                return ResourceManager.GetString("Shipments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        public static string Sponsor {
            get {
                return ResourceManager.GetString("Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Payment.
        /// </summary>
        public static string SupplierPayment {
            get {
                return ResourceManager.GetString("SupplierPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Payments.
        /// </summary>
        public static string SupplierPayments {
            get {
                return ResourceManager.GetString("SupplierPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Account.
        /// </summary>
        public static string SystemAccount {
            get {
                return ResourceManager.GetString("SystemAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Codes.
        /// </summary>
        public static string TaxCodes {
            get {
                return ResourceManager.GetString("TaxCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string Taxes {
            get {
                return ResourceManager.GetString("Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Group.
        /// </summary>
        public static string TaxGroup {
            get {
                return ResourceManager.GetString("TaxGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Groups.
        /// </summary>
        public static string TaxGroups {
            get {
                return ResourceManager.GetString("TaxGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID.
        /// </summary>
        public static string TaxID {
            get {
                return ResourceManager.GetString("TaxID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Periods.
        /// </summary>
        public static string TaxPeriods {
            get {
                return ResourceManager.GetString("TaxPeriods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Balance.
        /// </summary>
        public static string TrialBalance {
            get {
                return ResourceManager.GetString("TrialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trn Date.
        /// </summary>
        public static string TrnDate {
            get {
                return ResourceManager.GetString("TrnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Paid.
        /// </summary>
        public static string UnPaid {
            get {
                return ResourceManager.GetString("UnPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        public static string Void {
            get {
                return ResourceManager.GetString("Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Open Task.
        /// </summary>
        public static string YourOpenTask {
            get {
                return ResourceManager.GetString("YourOpenTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Remaining Tasks.
        /// </summary>
        public static string YourRemainingTasks {
            get {
                return ResourceManager.GetString("YourRemainingTasks", resourceCulture);
            }
        }
    }
}
