//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPKeeper.RdVat {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vat", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ERPKeeper.RdVat.ArrayOfAnyType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ERPKeeper.RdVat.ArrayOfString))]
    public partial class vat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vNIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vtinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vtitleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vBranchTitleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vBranchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vBranchNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vBuildingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vFloorNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vVillageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vRoomNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vHouseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vMooNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vSoiNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vStreetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vThambolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vAmphurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vPostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vBusinessFirstDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ERPKeeper.RdVat.ArrayOfAnyType vmsgerrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ERPKeeper.RdVat.ArrayOfAnyType vNID {
            get {
                return this.vNIDField;
            }
            set {
                if ((object.ReferenceEquals(this.vNIDField, value) != true)) {
                    this.vNIDField = value;
                    this.RaisePropertyChanged("vNID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ERPKeeper.RdVat.ArrayOfAnyType vtin {
            get {
                return this.vtinField;
            }
            set {
                if ((object.ReferenceEquals(this.vtinField, value) != true)) {
                    this.vtinField = value;
                    this.RaisePropertyChanged("vtin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ERPKeeper.RdVat.ArrayOfAnyType vtitleName {
            get {
                return this.vtitleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.vtitleNameField, value) != true)) {
                    this.vtitleNameField = value;
                    this.RaisePropertyChanged("vtitleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ERPKeeper.RdVat.ArrayOfAnyType vName {
            get {
                return this.vNameField;
            }
            set {
                if ((object.ReferenceEquals(this.vNameField, value) != true)) {
                    this.vNameField = value;
                    this.RaisePropertyChanged("vName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ERPKeeper.RdVat.ArrayOfAnyType vSurname {
            get {
                return this.vSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.vSurnameField, value) != true)) {
                    this.vSurnameField = value;
                    this.RaisePropertyChanged("vSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public ERPKeeper.RdVat.ArrayOfAnyType vBranchTitleName {
            get {
                return this.vBranchTitleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.vBranchTitleNameField, value) != true)) {
                    this.vBranchTitleNameField = value;
                    this.RaisePropertyChanged("vBranchTitleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ERPKeeper.RdVat.ArrayOfAnyType vBranchName {
            get {
                return this.vBranchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.vBranchNameField, value) != true)) {
                    this.vBranchNameField = value;
                    this.RaisePropertyChanged("vBranchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ERPKeeper.RdVat.ArrayOfAnyType vBranchNumber {
            get {
                return this.vBranchNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.vBranchNumberField, value) != true)) {
                    this.vBranchNumberField = value;
                    this.RaisePropertyChanged("vBranchNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public ERPKeeper.RdVat.ArrayOfAnyType vBuildingName {
            get {
                return this.vBuildingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.vBuildingNameField, value) != true)) {
                    this.vBuildingNameField = value;
                    this.RaisePropertyChanged("vBuildingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public ERPKeeper.RdVat.ArrayOfAnyType vFloorNumber {
            get {
                return this.vFloorNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.vFloorNumberField, value) != true)) {
                    this.vFloorNumberField = value;
                    this.RaisePropertyChanged("vFloorNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public ERPKeeper.RdVat.ArrayOfAnyType vVillageName {
            get {
                return this.vVillageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.vVillageNameField, value) != true)) {
                    this.vVillageNameField = value;
                    this.RaisePropertyChanged("vVillageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public ERPKeeper.RdVat.ArrayOfAnyType vRoomNumber {
            get {
                return this.vRoomNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.vRoomNumberField, value) != true)) {
                    this.vRoomNumberField = value;
                    this.RaisePropertyChanged("vRoomNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public ERPKeeper.RdVat.ArrayOfAnyType vHouseNumber {
            get {
                return this.vHouseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.vHouseNumberField, value) != true)) {
                    this.vHouseNumberField = value;
                    this.RaisePropertyChanged("vHouseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public ERPKeeper.RdVat.ArrayOfAnyType vMooNumber {
            get {
                return this.vMooNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.vMooNumberField, value) != true)) {
                    this.vMooNumberField = value;
                    this.RaisePropertyChanged("vMooNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public ERPKeeper.RdVat.ArrayOfAnyType vSoiName {
            get {
                return this.vSoiNameField;
            }
            set {
                if ((object.ReferenceEquals(this.vSoiNameField, value) != true)) {
                    this.vSoiNameField = value;
                    this.RaisePropertyChanged("vSoiName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public ERPKeeper.RdVat.ArrayOfAnyType vStreetName {
            get {
                return this.vStreetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.vStreetNameField, value) != true)) {
                    this.vStreetNameField = value;
                    this.RaisePropertyChanged("vStreetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public ERPKeeper.RdVat.ArrayOfAnyType vThambol {
            get {
                return this.vThambolField;
            }
            set {
                if ((object.ReferenceEquals(this.vThambolField, value) != true)) {
                    this.vThambolField = value;
                    this.RaisePropertyChanged("vThambol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public ERPKeeper.RdVat.ArrayOfAnyType vAmphur {
            get {
                return this.vAmphurField;
            }
            set {
                if ((object.ReferenceEquals(this.vAmphurField, value) != true)) {
                    this.vAmphurField = value;
                    this.RaisePropertyChanged("vAmphur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public ERPKeeper.RdVat.ArrayOfAnyType vProvince {
            get {
                return this.vProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.vProvinceField, value) != true)) {
                    this.vProvinceField = value;
                    this.RaisePropertyChanged("vProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public ERPKeeper.RdVat.ArrayOfAnyType vPostCode {
            get {
                return this.vPostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.vPostCodeField, value) != true)) {
                    this.vPostCodeField = value;
                    this.RaisePropertyChanged("vPostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public ERPKeeper.RdVat.ArrayOfAnyType vBusinessFirstDate {
            get {
                return this.vBusinessFirstDateField;
            }
            set {
                if ((object.ReferenceEquals(this.vBusinessFirstDateField, value) != true)) {
                    this.vBusinessFirstDateField = value;
                    this.RaisePropertyChanged("vBusinessFirstDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public ERPKeeper.RdVat.ArrayOfAnyType vmsgerr {
            get {
                return this.vmsgerrField;
            }
            set {
                if ((object.ReferenceEquals(this.vmsgerrField, value) != true)) {
                    this.vmsgerrField = value;
                    this.RaisePropertyChanged("vmsgerr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", ConfigurationName="RdVat.vatserviceRD3Soap")]
    public interface vatserviceRD3Soap {
        
        // CODEGEN: Generating message contract since element name username from namespace https://rdws.rd.go.th/serviceRD3/vatserviceRD3 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/serviceRD3/vatserviceRD3/Service", ReplyAction="*")]
        ERPKeeper.RdVat.ServiceResponse Service(ERPKeeper.RdVat.ServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/serviceRD3/vatserviceRD3/Service", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPKeeper.RdVat.ServiceResponse> ServiceAsync(ERPKeeper.RdVat.ServiceRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace https://rdws.rd.go.th/serviceRD3/vatserviceRD3 is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/serviceRD3/vatserviceRD3/ServiceArr", ReplyAction="*")]
        ERPKeeper.RdVat.ServiceArrResponse ServiceArr(ERPKeeper.RdVat.ServiceArrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rdws.rd.go.th/serviceRD3/vatserviceRD3/ServiceArr", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPKeeper.RdVat.ServiceArrResponse> ServiceArrAsync(ERPKeeper.RdVat.ServiceArrRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Service", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", Order=0)]
        public ERPKeeper.RdVat.ServiceRequestBody Body;
        
        public ServiceRequest() {
        }
        
        public ServiceRequest(ERPKeeper.RdVat.ServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    public partial class ServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TIN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ProvinceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int BranchNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int AmphurCode;
        
        public ServiceRequestBody() {
        }
        
        public ServiceRequestBody(string username, string password, string TIN, string Name, int ProvinceCode, int BranchNumber, int AmphurCode) {
            this.username = username;
            this.password = password;
            this.TIN = TIN;
            this.Name = Name;
            this.ProvinceCode = ProvinceCode;
            this.BranchNumber = BranchNumber;
            this.AmphurCode = AmphurCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceResponse", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", Order=0)]
        public ERPKeeper.RdVat.ServiceResponseBody Body;
        
        public ServiceResponse() {
        }
        
        public ServiceResponse(ERPKeeper.RdVat.ServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    public partial class ServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERPKeeper.RdVat.vat ServiceResult;
        
        public ServiceResponseBody() {
        }
        
        public ServiceResponseBody(ERPKeeper.RdVat.vat ServiceResult) {
            this.ServiceResult = ServiceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceArrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceArr", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", Order=0)]
        public ERPKeeper.RdVat.ServiceArrRequestBody Body;
        
        public ServiceArrRequest() {
        }
        
        public ServiceArrRequest(ERPKeeper.RdVat.ServiceArrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    public partial class ServiceArrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ERPKeeper.RdVat.ArrayOfString TINs;
        
        public ServiceArrRequestBody() {
        }
        
        public ServiceArrRequestBody(string username, string password, ERPKeeper.RdVat.ArrayOfString TINs) {
            this.username = username;
            this.password = password;
            this.TINs = TINs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ServiceArrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ServiceArrResponse", Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3", Order=0)]
        public ERPKeeper.RdVat.ServiceArrResponseBody Body;
        
        public ServiceArrResponse() {
        }
        
        public ServiceArrResponse(ERPKeeper.RdVat.ServiceArrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rdws.rd.go.th/serviceRD3/vatserviceRD3")]
    public partial class ServiceArrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ERPKeeper.RdVat.vat ServiceArrResult;
        
        public ServiceArrResponseBody() {
        }
        
        public ServiceArrResponseBody(ERPKeeper.RdVat.vat ServiceArrResult) {
            this.ServiceArrResult = ServiceArrResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface vatserviceRD3SoapChannel : ERPKeeper.RdVat.vatserviceRD3Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class vatserviceRD3SoapClient : System.ServiceModel.ClientBase<ERPKeeper.RdVat.vatserviceRD3Soap>, ERPKeeper.RdVat.vatserviceRD3Soap {
        
        public vatserviceRD3SoapClient() {
        }
        
        public vatserviceRD3SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public vatserviceRD3SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public vatserviceRD3SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public vatserviceRD3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPKeeper.RdVat.ServiceResponse ERPKeeper.RdVat.vatserviceRD3Soap.Service(ERPKeeper.RdVat.ServiceRequest request) {
            return base.Channel.Service(request);
        }
        
        public ERPKeeper.RdVat.vat Service(string username, string password, string TIN, string Name, int ProvinceCode, int BranchNumber, int AmphurCode) {
            ERPKeeper.RdVat.ServiceRequest inValue = new ERPKeeper.RdVat.ServiceRequest();
            inValue.Body = new ERPKeeper.RdVat.ServiceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TIN = TIN;
            inValue.Body.Name = Name;
            inValue.Body.ProvinceCode = ProvinceCode;
            inValue.Body.BranchNumber = BranchNumber;
            inValue.Body.AmphurCode = AmphurCode;
            ERPKeeper.RdVat.ServiceResponse retVal = ((ERPKeeper.RdVat.vatserviceRD3Soap)(this)).Service(inValue);
            return retVal.Body.ServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPKeeper.RdVat.ServiceResponse> ERPKeeper.RdVat.vatserviceRD3Soap.ServiceAsync(ERPKeeper.RdVat.ServiceRequest request) {
            return base.Channel.ServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPKeeper.RdVat.ServiceResponse> ServiceAsync(string username, string password, string TIN, string Name, int ProvinceCode, int BranchNumber, int AmphurCode) {
            ERPKeeper.RdVat.ServiceRequest inValue = new ERPKeeper.RdVat.ServiceRequest();
            inValue.Body = new ERPKeeper.RdVat.ServiceRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TIN = TIN;
            inValue.Body.Name = Name;
            inValue.Body.ProvinceCode = ProvinceCode;
            inValue.Body.BranchNumber = BranchNumber;
            inValue.Body.AmphurCode = AmphurCode;
            return ((ERPKeeper.RdVat.vatserviceRD3Soap)(this)).ServiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPKeeper.RdVat.ServiceArrResponse ERPKeeper.RdVat.vatserviceRD3Soap.ServiceArr(ERPKeeper.RdVat.ServiceArrRequest request) {
            return base.Channel.ServiceArr(request);
        }
        
        public ERPKeeper.RdVat.vat ServiceArr(string username, string password, ERPKeeper.RdVat.ArrayOfString TINs) {
            ERPKeeper.RdVat.ServiceArrRequest inValue = new ERPKeeper.RdVat.ServiceArrRequest();
            inValue.Body = new ERPKeeper.RdVat.ServiceArrRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TINs = TINs;
            ERPKeeper.RdVat.ServiceArrResponse retVal = ((ERPKeeper.RdVat.vatserviceRD3Soap)(this)).ServiceArr(inValue);
            return retVal.Body.ServiceArrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPKeeper.RdVat.ServiceArrResponse> ERPKeeper.RdVat.vatserviceRD3Soap.ServiceArrAsync(ERPKeeper.RdVat.ServiceArrRequest request) {
            return base.Channel.ServiceArrAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPKeeper.RdVat.ServiceArrResponse> ServiceArrAsync(string username, string password, ERPKeeper.RdVat.ArrayOfString TINs) {
            ERPKeeper.RdVat.ServiceArrRequest inValue = new ERPKeeper.RdVat.ServiceArrRequest();
            inValue.Body = new ERPKeeper.RdVat.ServiceArrRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.TINs = TINs;
            return ((ERPKeeper.RdVat.vatserviceRD3Soap)(this)).ServiceArrAsync(inValue);
        }
    }
}
